# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtn_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QDateTimeEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(962, 907)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(330, 310, 256, 41))
        self.txt_apellido = QLineEdit(self.centralwidget)
        self.txt_apellido.setObjectName(u"txt_apellido")
        self.txt_apellido.setGeometry(QRect(330, 260, 256, 41))
        self.btn_limpiar = QPushButton(self.centralwidget)
        self.btn_limpiar.setObjectName(u"btn_limpiar")
        self.btn_limpiar.setGeometry(QRect(810, 530, 93, 28))
        self.lbl_cedula = QLabel(self.centralwidget)
        self.lbl_cedula.setObjectName(u"lbl_cedula")
        self.lbl_cedula.setGeometry(QRect(240, 320, 81, 20))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_cedula.setFont(font)
        self.txt_peso = QLineEdit(self.centralwidget)
        self.txt_peso.setObjectName(u"txt_peso")
        self.txt_peso.setGeometry(QRect(330, 480, 256, 41))
        self.btn_agregar = QPushButton(self.centralwidget)
        self.btn_agregar.setObjectName(u"btn_agregar")
        self.btn_agregar.setGeometry(QRect(810, 480, 93, 28))
        self.lbl_email = QLabel(self.centralwidget)
        self.lbl_email.setObjectName(u"lbl_email")
        self.lbl_email.setGeometry(QRect(250, 430, 61, 20))
        self.lbl_email.setFont(font)
        self.txt_email = QLineEdit(self.centralwidget)
        self.txt_email.setObjectName(u"txt_email")
        self.txt_email.setGeometry(QRect(330, 420, 256, 41))
        self.btn_consultar = QPushButton(self.centralwidget)
        self.btn_consultar.setObjectName(u"btn_consultar")
        self.btn_consultar.setGeometry(QRect(530, 90, 93, 28))
        self.lbl_peso = QLabel(self.centralwidget)
        self.lbl_peso.setObjectName(u"lbl_peso")
        self.lbl_peso.setGeometry(QRect(260, 490, 55, 16))
        self.lbl_peso.setFont(font)
        self.lbl_personas = QLabel(self.centralwidget)
        self.lbl_personas.setObjectName(u"lbl_personas")
        self.lbl_personas.setGeometry(QRect(420, 30, 141, 21))
        self.lbl_personas.setFont(font)
        self.txt_nombre = QLineEdit(self.centralwidget)
        self.txt_nombre.setObjectName(u"txt_nombre")
        self.txt_nombre.setGeometry(QRect(330, 200, 256, 41))
        self.lbl_fecha_nacimiento = QLabel(self.centralwidget)
        self.lbl_fecha_nacimiento.setObjectName(u"lbl_fecha_nacimiento")
        self.lbl_fecha_nacimiento.setGeometry(QRect(130, 370, 191, 20))
        self.lbl_fecha_nacimiento.setFont(font)
        self.date_fecha_nacimiento = QDateEdit(self.centralwidget)
        self.date_fecha_nacimiento.setObjectName(u"date_fecha_nacimiento")
        self.date_fecha_nacimiento.setGeometry(QRect(330, 360, 151, 41))
        self.date_fecha_nacimiento.setProperty("showGroupSeparator", False)
        self.date_fecha_nacimiento.setMaximumDateTime(QDateTime(QDate(9999, 12, 30), QTime(23, 59, 59)))
        self.date_fecha_nacimiento.setCurrentSection(QDateTimeEdit.MonthSection)
        self.date_fecha_nacimiento.setCalendarPopup(True)
        self.date_fecha_nacimiento.setCurrentSectionIndex(0)
        self.date_fecha_nacimiento.setDate(QDate(2000, 1, 1))
        self.txt_estatura = QLineEdit(self.centralwidget)
        self.txt_estatura.setObjectName(u"txt_estatura")
        self.txt_estatura.setGeometry(QRect(330, 540, 256, 41))
        self.lbl_apellido = QLabel(self.centralwidget)
        self.lbl_apellido.setObjectName(u"lbl_apellido")
        self.lbl_apellido.setGeometry(QRect(230, 270, 91, 21))
        self.lbl_apellido.setFont(font)
        self.lbl_estatura = QLabel(self.centralwidget)
        self.lbl_estatura.setObjectName(u"lbl_estatura")
        self.lbl_estatura.setGeometry(QRect(220, 550, 91, 20))
        self.lbl_estatura.setFont(font)
        self.lbl_nombre = QLabel(self.centralwidget)
        self.lbl_nombre.setObjectName(u"lbl_nombre")
        self.lbl_nombre.setGeometry(QRect(230, 210, 91, 20))
        self.lbl_nombre.setFont(font)
        self.lbl_consulta_cedula = QLabel(self.centralwidget)
        self.lbl_consulta_cedula.setObjectName(u"lbl_consulta_cedula")
        self.lbl_consulta_cedula.setGeometry(QRect(40, 100, 211, 20))
        self.lbl_consulta_cedula.setFont(font)
        self.txt_consulta_cedula = QLineEdit(self.centralwidget)
        self.txt_consulta_cedula.setObjectName(u"txt_consulta_cedula")
        self.txt_consulta_cedula.setGeometry(QRect(250, 80, 256, 41))
        self.lbl_edad_resultado = QLabel(self.centralwidget)
        self.lbl_edad_resultado.setObjectName(u"lbl_edad_resultado")
        self.lbl_edad_resultado.setGeometry(QRect(170, 760, 91, 20))
        self.lbl_edad_resultado.setFont(font)
        self.lbl_media_resultado = QLabel(self.centralwidget)
        self.lbl_media_resultado.setObjectName(u"lbl_media_resultado")
        self.lbl_media_resultado.setGeometry(QRect(340, 760, 91, 20))
        self.lbl_media_resultado.setFont(font)
        self.lbl_mediana_resultado = QLabel(self.centralwidget)
        self.lbl_mediana_resultado.setObjectName(u"lbl_mediana_resultado")
        self.lbl_mediana_resultado.setGeometry(QRect(510, 760, 91, 20))
        self.lbl_mediana_resultado.setFont(font)
        self.lbl_moda_resultado = QLabel(self.centralwidget)
        self.lbl_moda_resultado.setObjectName(u"lbl_moda_resultado")
        self.lbl_moda_resultado.setGeometry(QRect(720, 760, 91, 20))
        self.lbl_moda_resultado.setFont(font)
        self.btn_calcular = QPushButton(self.centralwidget)
        self.btn_calcular.setObjectName(u"btn_calcular")
        self.btn_calcular.setGeometry(QRect(410, 650, 93, 28))
        self.lbl_calcular_edad = QLabel(self.centralwidget)
        self.lbl_calcular_edad.setObjectName(u"lbl_calcular_edad")
        self.lbl_calcular_edad.setGeometry(QRect(150, 710, 101, 31))
        self.lbl_calcular_media = QLabel(self.centralwidget)
        self.lbl_calcular_media.setObjectName(u"lbl_calcular_media")
        self.lbl_calcular_media.setGeometry(QRect(330, 710, 101, 31))
        self.lbl_calcular_medina = QLabel(self.centralwidget)
        self.lbl_calcular_medina.setObjectName(u"lbl_calcular_medina")
        self.lbl_calcular_medina.setGeometry(QRect(500, 710, 101, 31))
        self.lbl_calcular_moda = QLabel(self.centralwidget)
        self.lbl_calcular_moda.setObjectName(u"lbl_calcular_moda")
        self.lbl_calcular_moda.setGeometry(QRect(690, 710, 101, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 962, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_limpiar.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.lbl_cedula.setText(QCoreApplication.translate("MainWindow", u"Cedula:", None))
        self.btn_agregar.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.lbl_email.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.btn_consultar.setText(QCoreApplication.translate("MainWindow", u"Consultar", None))
        self.lbl_peso.setText(QCoreApplication.translate("MainWindow", u"Peso:", None))
        self.lbl_personas.setText(QCoreApplication.translate("MainWindow", u"PERSONAS", None))
        self.lbl_fecha_nacimiento.setText(QCoreApplication.translate("MainWindow", u"Fecha Nacimiento:", None))
        self.lbl_apellido.setText(QCoreApplication.translate("MainWindow", u"Apellido:", None))
        self.lbl_estatura.setText(QCoreApplication.translate("MainWindow", u"Estatura:", None))
        self.lbl_nombre.setText(QCoreApplication.translate("MainWindow", u"Nombre:", None))
        self.lbl_consulta_cedula.setText(QCoreApplication.translate("MainWindow", u"Ingrese su cedula:", None))
        self.lbl_edad_resultado.setText(QCoreApplication.translate("MainWindow", u"Edad", None))
        self.lbl_media_resultado.setText(QCoreApplication.translate("MainWindow", u"Media", None))
        self.lbl_mediana_resultado.setText(QCoreApplication.translate("MainWindow", u"Mediana", None))
        self.lbl_moda_resultado.setText(QCoreApplication.translate("MainWindow", u"Moda", None))
        self.btn_calcular.setText(QCoreApplication.translate("MainWindow", u"Calcular", None))
        self.lbl_calcular_edad.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.lbl_calcular_media.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.lbl_calcular_medina.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.lbl_calcular_moda.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
    # retranslateUi

